params:

  
  seed: ${...seed}

  algo:
    name: sea_ac # a2c_continuous # pixel_ac

  model:
    name: continuous_sea

  network:
    name: actor_critic_sea # actor_critic # actor_critic_pixel
    separate: False

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0. # std = 1.
        fixed_sigma: true

    mlp:
      units: [512, 256, 128]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

    history:
      units: [512, 128, 32]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    device: ${resolve_default:cuda:0,${....rl_device}}
    name: ${resolve_default:A1ballShoot,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    ppo: True
    mixed_precision: True
    normalize_input: True # True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.995
    tau: 0.95
    e_clip: 0.2
    entropy_coef: 0.001
    learning_rate: 3.e-4 # overwritten by adaptive lr_schedule
    lr_schedule: adaptive
    kl_threshold: 0.008 # target kl for adaptive lr
    truncate_grads: True
    grad_norm: 1.
    horizon_length: 24
    minibatch_size: 32000 # should not be too big?
    # minibatch_size_per_env: 6
    mini_epochs: 5
    critic_coef: 2
    clip_value: True
    seq_len: 4 # only for rnn
    bounds_loss_coef: 0.001
    estimate_coef: 1.0

    max_epochs: ${resolve_default:20000,${....max_iterations}}
    save_best_after: 200
    score_to_win: 20000
    save_frequency: 1000
    print_stats: True

    player:
      games_num: 50000
